-- MySQL Script generated by MySQL Workbench
-- Sat May  6 23:34:41 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `clave` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nom_usu` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` TEXT NOT NULL,
  PRIMARY KEY (`id_cliente`),
  CONSTRAINT `id_usuario_cliente`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idUSUARIO_idx` ON `mydb`.`cliente` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_administrador`),
  CONSTRAINT `id_usuario_admin`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idUSUARIO_idx` ON `mydb`.`administrador` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`carrito` (
  `id_carrito` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `monto` FLOAT NOT NULL,
  `cantidad` INT NOT NULL,
  `medio_pago` VARCHAR(45) NULL,
  PRIMARY KEY (`id_carrito`),
  CONSTRAINT `idCLIENTE`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idCLIENTE_idx` ON `mydb`.`carrito` (`id_cliente` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL,
  `nombre_categoria` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bebidas` (
  `id_bebidas` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `stock` DECIMAL(18) NOT NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  `id_categoria` INT NOT NULL,
  `imagen` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`id_bebidas`),
  CONSTRAINT `idcategoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idcategoria_idx` ON `mydb`.`bebidas` (`id_categoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id_pedido` INT NOT NULL,
  `id_bebidas` INT NOT NULL,
  `id_carrito` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `n_de_factura` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  CONSTRAINT `idBEBIDAS`
    FOREIGN KEY (`id_bebidas`)
    REFERENCES `mydb`.`bebidas` (`id_bebidas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCARRITO`
    FOREIGN KEY (`id_carrito`)
    REFERENCES `mydb`.`carrito` (`id_carrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idBEBIDAS_idx` ON `mydb`.`pedido` (`id_bebidas` ASC) VISIBLE;

CREATE INDEX `idCARRITO_idx` ON `mydb`.`pedido` (`id_carrito` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
