# Generated by Django 4.2.1 on 2023-06-20 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bebidas',
            fields=[
                ('id_bebidas', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=45)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bebidas/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('medio_pago', models.CharField(max_length=45)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('numero_factura', models.IntegerField(unique=True)),
                ('id_bebidas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendavirtualHS.bebidas')),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendavirtualHS.carrito')),
            ],
        ),
        migrations.AddField(
            model_name='bebidas',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TiendavirtualHS.categoria'),
        ),
    ]
