# Generated by Django 4.2.1 on 2023-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TiendavirtualHS', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebidas',
            name='codigo',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
